class_name StudioContentManifest
extends RefCounted
## Content manifest: what content packs/versions this build contains.
## Generated by the cook pipeline (never hand-edited). Empty manifest is valid
## for bootstrap projects.

const MANIFEST_PATH: String = "res://content_manifest.json"

var manifest: Dictionary = {"schema": 1, "packs": {}}


func load_manifest(path: String = MANIFEST_PATH) -> bool:
	if not FileAccess.file_exists(path):
		return false
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if parsed is Dictionary:
		manifest = parsed
		return true
	return false


func packs() -> Dictionary:
	var value: Variant = manifest.get("packs", {})
	return value if value is Dictionary else {}


func pack_version(pack_name: String) -> String:
	var pack: Variant = packs().get(pack_name, {})
	if pack is Dictionary:
		return str((pack as Dictionary).get("version", ""))
	return ""
