#!/usr/bin/env python3
"""Turn render-probe results into the renderer status table the docs publish.

The recurring, and fair, criticism of this project has been claims running ahead
of proof. The durable fix is not to write more careful prose -- it is to stop
writing the status by hand at all. This renders a status table straight from
render-probe JSON, so a documented renderer state cannot be more optimistic than
the last measurement.

Two rules the generator enforces, because they are the two ways this kind of
table goes wrong:

  * "renders" means pixels. A probe that compiled every shader and produced a
    flat canvas is reported as NOT rendering, however good the error count looks.
  * A missing measurement is reported as "not measured", never as a pass.

  render_report.py --probe DIR [--out FILE] [--check]

`--check` re-renders the table and exits non-zero if the file on disk differs,
which is the form CI wants.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MARK_BEGIN = "<!-- BEGIN GENERATED: renderer-status -->"
MARK_END = "<!-- END GENERATED: renderer-status -->"


class ReportError(RuntimeError):
    """A probe result was missing or malformed."""


def load_probes(probe_dir: Path) -> list[dict]:
    if not probe_dir.is_dir():
        raise ReportError(f"probe directory does not exist: {probe_dir}")
    probes = []
    for path in sorted(probe_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ReportError(f"{path.name}: {exc}") from exc
        if "frame_rendered" not in data:
            # Not a probe result; skip rather than guess.
            continue
        data["_source"] = path.name
        probes.append(data)
    if not probes:
        raise ReportError(f"no render-probe results found in {probe_dir}")
    return probes


def _verdict(probe: dict) -> str:
    """One word, chosen so it cannot flatter the result.

    Compiling cleanly is not rendering, and this is the distinction the whole
    Forward+ investigation turned on.
    """
    if probe.get("frame_rendered") is not True:
        return "does not render"
    errors = probe.get("gpu_validation_errors")
    if errors is None:
        # A frame with an unmeasured error count is not a clean frame. Saying so
        # is the whole reason this is generated rather than written by hand.
        return "renders, errors not measured"
    if errors > 0:
        return "renders, with validation errors"
    return "renders clean"


def _adapter(probe: dict) -> str:
    adapter = probe.get("adapter") or {}
    vendor = adapter.get("vendor") or "unknown"
    arch = adapter.get("architecture") or ""
    return f"{vendor} {arch}".strip()


def render_table(probes: list[dict]) -> str:
    lines = [
        MARK_BEGIN,
        "",
        "<!-- Generated by tools/verification/render_report.py from render-probe",
        "     results. Do not edit by hand: `just renderer-report` regenerates it,",
        "     and CI fails when it drifts from the measurements. -->",
        "",
        "| Configuration | Frame rendered | Validation errors | Adapter | Evidence |",
        "| --- | --- | --- | --- | --- |",
    ]
    for probe in probes:
        label = probe.get("label", "?")
        errors = probe.get("gpu_validation_errors")
        by_class = probe.get("gpu_validation_by_class") or {}
        detail = ""
        if by_class:
            detail = " (" + ", ".join(f"{k} {v}" for k, v in sorted(by_class.items())) + ")"
        errors_cell = "not measured" if errors is None else f"{errors}{detail}"
        lines.append(
            "| `{label}` | **{verdict}** | {errors} | {adapter} | `{src}` |".format(
                label=label,
                verdict=_verdict(probe),
                errors=errors_cell,
                adapter=_adapter(probe),
                src=probe.get("_source", "?"),
            )
        )
    lines += ["", MARK_END]
    return "\n".join(lines)


def splice(existing: str, table: str) -> str:
    """Replace the generated block in a document, or append it if absent."""
    start = existing.find(MARK_BEGIN)
    end = existing.find(MARK_END)
    if start == -1 or end == -1 or end < start:
        separator = "" if existing.endswith("\n\n") or not existing else "\n"
        return existing + separator + table + "\n"
    return existing[:start] + table + existing[end + len(MARK_END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--probe", required=True, help="directory of render-probe *.json results")
    parser.add_argument("--out", help="markdown file to splice the table into")
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if --out differs from the generated table",
    )
    args = parser.parse_args(argv)

    try:
        probes = load_probes(Path(args.probe))
    except ReportError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    table = render_table(probes)

    if not args.out:
        print(table)
        return 0

    out = Path(args.out)
    current = out.read_text(encoding="utf-8") if out.is_file() else ""
    updated = splice(current, table)
    if args.check:
        if current != updated:
            print(
                f"error: {out} is stale — regenerate with `just renderer-report`",
                file=sys.stderr,
            )
            return 1
        print(f"[report] {out} matches the measurements")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(updated, encoding="utf-8")
    print(f"[report] wrote {len(probes)} probe result(s) into {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
